package filament

// Filament represents an OrcaSlicer filament profile.
type Filament struct {
	InfoFile string `json:"-"`

	// Stable inferred types from Orca profile samples
	AdaptivePressureAdvance                  []string         `json:"adaptive_pressure_advance,omitempty"`
	AdaptivePressureAdvanceBridges           []string         `json:"adaptive_pressure_advance_bridges,omitempty"`
	AdaptivePressureAdvanceModel             []string         `json:"adaptive_pressure_advance_model,omitempty"`
	AdaptivePressureAdvanceOverhangs         []string         `json:"adaptive_pressure_advance_overhangs,omitempty"`
	AdditionalCoolingFanSpeedUnseal          []string         `json:"additional_cooling_fan_speed_unseal,omitempty"`
	BedTemperatureDifference                 []string         `json:"bed_temperature_difference,omitempty"`
	BedType                                  []string         `json:"bed_type,omitempty"`
	BoxTemperature                           []string         `json:"box_temperature,omitempty"`
	BoxTemperatureRangeHigh                  []string         `json:"box_temperature_range_high,omitempty"`
	BoxTemperatureRangeLow                   []string         `json:"box_temperature_range_low,omitempty"`
	ChamberTemperatures                      []string         `json:"chamber_temperatures,omitempty"`
	CircleCompensationSpeed                  []string         `json:"circle_compensation_speed,omitempty"`
	CompatiblePrinters                       []string         `json:"compatible_printers,omitempty"`
	CompatiblePrintersCondition              string           `json:"compatible_printers_condition,omitempty"`
	CompatiblePrints                         []string         `json:"compatible_prints,omitempty"`
	CompatiblePrintsCondition                string           `json:"compatible_prints_condition,omitempty"`
	CoolSpecialCdsFanSpeed                   string           `json:"cool_special_cds_fan_speed,omitempty"`
	CounterCoef1                             []string         `json:"counter_coef_1,omitempty"`
	CounterCoef2                             []string         `json:"counter_coef_2,omitempty"`
	CounterCoef3                             []string         `json:"counter_coef_3,omitempty"`
	CounterLimitMax                          []string         `json:"counter_limit_max,omitempty"`
	CounterLimitMin                          []string         `json:"counter_limit_min,omitempty"`
	Data                                     []map[string]any `json:"data,omitempty"`
	Description                              string           `json:"description,omitempty"`
	DiameterLimit                            []string         `json:"diameter_limit,omitempty"`
	EnableVolumeFan                          []string         `json:"enable_volume_fan,omitempty"`
	ExtruderRotationVolume                   string           `json:"extruder_rotation_volume,omitempty"`
	FilamentAdaptiveVolumetricSpeed          []string         `json:"filament_adaptive_volumetric_speed,omitempty"`
	FilamentAdhesivenessCategory             []string         `json:"filament_adhesiveness_category,omitempty"`
	FilamentChangeLength                     []string         `json:"filament_change_length,omitempty"`
	FilamentChangeLengthNc                   []string         `json:"filament_change_length_nc,omitempty"`
	FilamentCost                             []string         `json:"filament_cost,omitempty"`
	FilamentDensity                          []string         `json:"filament_density,omitempty"`
	FilamentEnableOverhangSpeed              []string         `json:"filament_enable_overhang_speed,omitempty"`
	FilamentEndGcode                         []string         `json:"filament_end_gcode,omitempty"`
	FilamentExtruderId                       []string         `json:"filament_extruder_id,omitempty"`
	FilamentExtruderVariant                  []string         `json:"filament_extruder_variant,omitempty"`
	FilamentFlowRatioInitialLayer            []string         `json:"filament_flow_ratio_initial_layer,omitempty"`
	FilamentFlushTemp                        []string         `json:"filament_flush_temp,omitempty"`
	FilamentFlushVolumetricSpeed             []string         `json:"filament_flush_volumetric_speed,omitempty"`
	FilamentId                               string           `json:"filament_id,omitempty"`
	FilamentLongRetractionsWhenCut           []string         `json:"filament_long_retractions_when_cut,omitempty"`
	FilamentLongRetractionsWhenEc            []string         `json:"filament_long_retractions_when_ec,omitempty"`
	FilamentMaxVolumetricSpeed               []string         `json:"filament_max_volumetric_speed,omitempty"`
	FilamentOverhang14Speed                  []string         `json:"filament_overhang_1_4_speed,omitempty"`
	FilamentOverhang24Speed                  []string         `json:"filament_overhang_2_4_speed,omitempty"`
	FilamentOverhang34Speed                  []string         `json:"filament_overhang_3_4_speed,omitempty"`
	FilamentOverhang44Speed                  []string         `json:"filament_overhang_4_4_speed,omitempty"`
	FilamentOverhangTotallySpeed             []string         `json:"filament_overhang_totally_speed,omitempty"`
	FilamentPreCoolingTemperature            []string         `json:"filament_pre_cooling_temperature,omitempty"`
	FilamentPreCoolingTemperatureNc          []string         `json:"filament_pre_cooling_temperature_nc,omitempty"`
	FilamentPrimeVolume                      []string         `json:"filament_prime_volume,omitempty"`
	FilamentPrimeVolumeNc                    []string         `json:"filament_prime_volume_nc,omitempty"`
	FilamentPrintable                        []string         `json:"filament_printable,omitempty"`
	FilamentRammingTravelTime                []string         `json:"filament_ramming_travel_time,omitempty"`
	FilamentRammingTravelTimeNc              []string         `json:"filament_ramming_travel_time_nc,omitempty"`
	FilamentRammingVolumetricSpeed           []string         `json:"filament_ramming_volumetric_speed,omitempty"`
	FilamentRammingVolumetricSpeedNc         []string         `json:"filament_ramming_volumetric_speed_nc,omitempty"`
	FilamentRetractionDistancesWhenCut       []string         `json:"filament_retraction_distances_when_cut,omitempty"`
	FilamentRetractionDistancesWhenEc        []string         `json:"filament_retraction_distances_when_ec,omitempty"`
	FilamentScarfGap                         []string         `json:"filament_scarf_gap,omitempty"`
	FilamentScarfHeight                      []string         `json:"filament_scarf_height,omitempty"`
	FilamentScarfLength                      []string         `json:"filament_scarf_length,omitempty"`
	FilamentScarfSeamType                    []string         `json:"filament_scarf_seam_type,omitempty"`
	FilamentSettingsId                       []string         `json:"filament_settings_id,omitempty"`
	FilamentStampingDistance                 []string         `json:"filament_stamping_distance,omitempty"`
	FilamentStampingLoadingSpeed             []string         `json:"filament_stamping_loading_speed,omitempty"`
	FilamentStartGcode                       []string         `json:"filament_start_gcode,omitempty"`
	FilamentTowerInterfacePreExtrusionDist   []string         `json:"filament_tower_interface_pre_extrusion_dist,omitempty"`
	FilamentTowerInterfacePreExtrusionLength []string         `json:"filament_tower_interface_pre_extrusion_length,omitempty"`
	FilamentTowerInterfacePrintTemp          []string         `json:"filament_tower_interface_print_temp,omitempty"`
	FilamentTowerInterfacePurgeVolume        []string         `json:"filament_tower_interface_purge_volume,omitempty"`
	FilamentTowerIroningArea                 []string         `json:"filament_tower_ironing_area,omitempty"`
	FilamentVelocityAdaptationFactor         []string         `json:"filament_velocity_adaptation_factor,omitempty"`
	FilamentVendor                           []string         `json:"filament_vendor,omitempty"`
	FirstLayerTemperature                    []string         `json:"first_layer_temperature,omitempty"`
	FirstXLayerFanSpeed                      []string         `json:"first_x_layer_fan_speed,omitempty"`
	From                                     string           `json:"from,omitempty"`
	HoleCoef1                                []string         `json:"hole_coef_1,omitempty"`
	HoleCoef2                                []string         `json:"hole_coef_2,omitempty"`
	HoleCoef3                                []string         `json:"hole_coef_3,omitempty"`
	HoleLimitMax                             []string         `json:"hole_limit_max,omitempty"`
	HoleLimitMin                             []string         `json:"hole_limit_min,omitempty"`
	ImpactStrengthZ                          []string         `json:"impact_strength_z,omitempty"`
	Inherits                                 string           `json:"inherits,omitempty"`
	Instantiation                            string           `json:"instantiation,omitempty"`
	InternalBridgeFanSpeed                   []string         `json:"internal_bridge_fan_speed,omitempty"`
	IroningFanSpeed                          []string         `json:"ironing_fan_speed,omitempty"`
	LongRetractionsWhenEc                    []string         `json:"long_retractions_when_ec,omitempty"`
	MixingStepperRotationVolume              string           `json:"mixing_stepper_rotation_volume,omitempty"`
	MultiZone1InitialLayer                   string           `json:"multi_zone_1_initial_layer,omitempty"`
	MultiZone1Temperature                    string           `json:"multi_zone_1_temperature,omitempty"`
	MultiZone2InitialLayer                   string           `json:"multi_zone_2_initial_layer,omitempty"`
	MultiZone2Temperature                    string           `json:"multi_zone_2_temperature,omitempty"`
	MultiZone3InitialLayer                   string           `json:"multi_zone_3_initial_layer,omitempty"`
	MultiZone3Temperature                    string           `json:"multi_zone_3_temperature,omitempty"`
	Name                                     string           `json:"name,omitempty"`
	NozzleTemperatureIntialLayer             string           `json:"nozzle_temperature_intial_layer,omitempty"`
	OverrideProcessOverhangSpeed             []string         `json:"override_process_overhang_speed,omitempty"`
	PelletFlowCoefficient                    []string         `json:"pellet_flow_coefficient,omitempty"`
	PreStartFanTime                          []string         `json:"pre_start_fan_time,omitempty"`
	RenamedFrom                              string           `json:"renamed_from,omitempty"`
	RetractionDistancesWhenEc                []string         `json:"retraction_distances_when_ec,omitempty"`
	SettingId                                string           `json:"setting_id,omitempty"`
	SettingsId                               string           `json:"settings_id,omitempty"`
	SupertackPlateTemp                       []string         `json:"supertack_plate_temp,omitempty"`
	SupertackPlateTempInitialLayer           []string         `json:"supertack_plate_temp_initial_layer,omitempty"`
	TemperatureVitrification                 []string         `json:"temperature_vitrification,omitempty"`
	TexturedCoolPlateTemp                    []string         `json:"textured_cool_plate_temp,omitempty"`
	TexturedCoolPlateTempInitialLayer        []string         `json:"textured_cool_plate_temp_initial_layer,omitempty"`
	Total                                    int              `json:"total,omitempty"`
	Type                                     string           `json:"type,omitempty"`
	VolumetricSpeedCoefficients              []string         `json:"volumetric_speed_coefficients,omitempty"`

	// Mixed-shape keys across profiles (kept flexible)
	ActivateAirFiltration            any `json:"activate_air_filtration,omitempty"`
	ActivateChamberTempControl       any `json:"activate_chamber_temp_control,omitempty"`
	AdditionalCoolingFanSpeed        any `json:"additional_cooling_fan_speed,omitempty"`
	ChamberTemperature               any `json:"chamber_temperature,omitempty"`
	CloseFanTheFirstXLayers          any `json:"close_fan_the_first_x_layers,omitempty"`
	CompletePrintExhaustFanSpeed     any `json:"complete_print_exhaust_fan_speed,omitempty"`
	CoolPlateTemp                    any `json:"cool_plate_temp,omitempty"`
	CoolPlateTempInitialLayer        any `json:"cool_plate_temp_initial_layer,omitempty"`
	DefaultFilamentColour            any `json:"default_filament_colour,omitempty"`
	DontSlowDownOuterWall            any `json:"dont_slow_down_outer_wall,omitempty"`
	DuringPrintExhaustFanSpeed       any `json:"during_print_exhaust_fan_speed,omitempty"`
	EnableOverhangBridgeFan          any `json:"enable_overhang_bridge_fan,omitempty"`
	EnablePressureAdvance            any `json:"enable_pressure_advance,omitempty"`
	EngPlateTemp                     any `json:"eng_plate_temp,omitempty"`
	EngPlateTempInitialLayer         any `json:"eng_plate_temp_initial_layer,omitempty"`
	FanCoolingLayerTime              any `json:"fan_cooling_layer_time,omitempty"`
	FanMaxSpeed                      any `json:"fan_max_speed,omitempty"`
	FanMinSpeed                      any `json:"fan_min_speed,omitempty"`
	FilamentCoolingFinalSpeed        any `json:"filament_cooling_final_speed,omitempty"`
	FilamentCoolingInitialSpeed      any `json:"filament_cooling_initial_speed,omitempty"`
	FilamentCoolingMoves             any `json:"filament_cooling_moves,omitempty"`
	FilamentDeretractionSpeed        any `json:"filament_deretraction_speed,omitempty"`
	FilamentDiameter                 any `json:"filament_diameter,omitempty"`
	FilamentFlowRatio                any `json:"filament_flow_ratio,omitempty"`
	FilamentIsSupport                any `json:"filament_is_support,omitempty"`
	FilamentLoadTime                 any `json:"filament_load_time,omitempty"`
	FilamentLoadingSpeed             any `json:"filament_loading_speed,omitempty"`
	FilamentLoadingSpeedStart        any `json:"filament_loading_speed_start,omitempty"`
	FilamentMinimalPurgeOnWipeTower  any `json:"filament_minimal_purge_on_wipe_tower,omitempty"`
	FilamentMultitoolRamming         any `json:"filament_multitool_ramming,omitempty"`
	FilamentMultitoolRammingFlow     any `json:"filament_multitool_ramming_flow,omitempty"`
	FilamentMultitoolRammingVolume   any `json:"filament_multitool_ramming_volume,omitempty"`
	FilamentNotes                    any `json:"filament_notes,omitempty"`
	FilamentRammingParameters        any `json:"filament_ramming_parameters,omitempty"`
	FilamentRetractBeforeWipe        any `json:"filament_retract_before_wipe,omitempty"`
	FilamentRetractLiftAbove         any `json:"filament_retract_lift_above,omitempty"`
	FilamentRetractLiftBelow         any `json:"filament_retract_lift_below,omitempty"`
	FilamentRetractLiftEnforce       any `json:"filament_retract_lift_enforce,omitempty"`
	FilamentRetractRestartExtra      any `json:"filament_retract_restart_extra,omitempty"`
	FilamentRetractWhenChangingLayer any `json:"filament_retract_when_changing_layer,omitempty"`
	FilamentRetractionLength         any `json:"filament_retraction_length,omitempty"`
	FilamentRetractionMinimumTravel  any `json:"filament_retraction_minimum_travel,omitempty"`
	FilamentRetractionSpeed          any `json:"filament_retraction_speed,omitempty"`
	FilamentShrink                   any `json:"filament_shrink,omitempty"`
	FilamentShrinkageCompensationZ   any `json:"filament_shrinkage_compensation_z,omitempty"`
	FilamentSoluble                  any `json:"filament_soluble,omitempty"`
	FilamentToolchangeDelay          any `json:"filament_toolchange_delay,omitempty"`
	FilamentType                     any `json:"filament_type,omitempty"`
	FilamentUnloadTime               any `json:"filament_unload_time,omitempty"`
	FilamentUnloadingSpeed           any `json:"filament_unloading_speed,omitempty"`
	FilamentUnloadingSpeedStart      any `json:"filament_unloading_speed_start,omitempty"`
	FilamentWipe                     any `json:"filament_wipe,omitempty"`
	FilamentWipeDistance             any `json:"filament_wipe_distance,omitempty"`
	FilamentZHop                     any `json:"filament_z_hop,omitempty"`
	FilamentZHopTypes                any `json:"filament_z_hop_types,omitempty"`
	FullFanSpeedLayer                any `json:"full_fan_speed_layer,omitempty"`
	HotPlateTemp                     any `json:"hot_plate_temp,omitempty"`
	HotPlateTempInitialLayer         any `json:"hot_plate_temp_initial_layer,omitempty"`
	IdleTemperature                  any `json:"idle_temperature,omitempty"`
	NozzleTemperature                any `json:"nozzle_temperature,omitempty"`
	NozzleTemperatureInitialLayer    any `json:"nozzle_temperature_initial_layer,omitempty"`
	NozzleTemperatureRangeHigh       any `json:"nozzle_temperature_range_high,omitempty"`
	NozzleTemperatureRangeLow        any `json:"nozzle_temperature_range_low,omitempty"`
	OverhangFanSpeed                 any `json:"overhang_fan_speed,omitempty"`
	OverhangFanThreshold             any `json:"overhang_fan_threshold,omitempty"`
	PressureAdvance                  any `json:"pressure_advance,omitempty"`
	ReduceFanStopStartFreq           any `json:"reduce_fan_stop_start_freq,omitempty"`
	RequiredNozzleHrc                any `json:"required_nozzle_HRC,omitempty"`
	SlowDownForLayerCooling          any `json:"slow_down_for_layer_cooling,omitempty"`
	SlowDownLayerTime                any `json:"slow_down_layer_time,omitempty"`
	SlowDownMinSpeed                 any `json:"slow_down_min_speed,omitempty"`
	SupportMaterialInterfaceFanSpeed any `json:"support_material_interface_fan_speed,omitempty"`
	TexturedPlateTemp                any `json:"textured_plate_temp,omitempty"`
	TexturedPlateTempInitialLayer    any `json:"textured_plate_temp_initial_layer,omitempty"`
}
