package process

// Process is the struct for the process
type Process struct {
	// Internal/computed
	NozzleSize  float64 `json:"-"`
	LayerHeight float64 `json:"-"`
	InfoFile    string  `json:"-"`

	// Metadata
	// InheritedFrom map[string]string `json:"_inherited_from,omitempty"`
	InheritedFrom map[string]string `json:"-"`

	// Required identity
	Name            string `json:"name"`
	From            string `json:"from"`
	Inherits        string `json:"inherits"`
	Version         string `json:"version"`
	IsCustomDefined string `json:"is_custom_defined"`

	// General print behavior
	PrintSettingsId         string `json:"print_settings_id,omitempty"`
	BrimType                string `json:"brim_type"`
	SkirtLoops              string `json:"skirt_loops"`
	SkirtSpeed              string `json:"skirt_speed"`
	OnlyOneWallTop          string `json:"only_one_wall_top,omitempty"`
	WallLoops               string `json:"wall_loops,omitempty"`
	BottomShellLayers       string `json:"bottom_shell_layers,omitempty"`
	TopShellLayers          string `json:"top_shell_layers,omitempty"`
	BottomShellThickness    string `json:"bottom_shell_thickness,omitempty"`
	TopShellThickness       string `json:"top_shell_thickness,omitempty"`
	Resolution              string `json:"resolution,omitempty"`
	RaftContactDistance     string `json:"raft_contact_distance,omitempty"`
	RaftLayers              string `json:"raft_layers,omitempty"`
	ElefantFootCompensation string `json:"elefant_foot_compensation,omitempty"`
	PreciseOuterWall        string `json:"precise_outer_wall,omitempty"`
	ReverseOnEven           string `json:"overhang_reverse,omitempty"`
	XyHoleCompensation      string `json:"xy_hole_compensation,omitempty"`

	// Seam / flow tuning
	SeamSlopeType                                string `json:"seam_slope_type,omitempty"`
	SeamSlopeConditional                         string `json:"seam_slope_conditional,omitempty"`
	AccelToDecelEnable                           string `json:"accel_to_decel_enable,omitempty"`
	ExtrusionRateSmoothing                       string `json:"max_volumetric_extrusion_rate_slope,omitempty"`
	MaxVolumetricExtrusionRateSlopeSegmentLength string `json:"max_volumetric_extrusion_rate_slope_segment_length,omitempty"`

	// Infill
	SparseInfillDensity        string `json:"sparse_infill_density,omitempty"`
	SparseInfillPattern        string `json:"sparse_infill_pattern,omitempty"`
	InfillAnchor               string `json:"infill_anchor,omitempty"`
	InfillAnchorMax            string `json:"infill_anchor_max,omitempty"`
	InfillWallOverlap          string `json:"infill_wall_overlap,omitempty"`
	TopBottomInfillWallOverlap string `json:"top_bottom_infill_wall_overlap,omitempty"`

	// Support
	SupportAngle                        string `json:"support_angle,omitempty"`
	SupportBasePattern                  string `json:"support_base_pattern,omitempty"`
	SupportBasePatternSpacing           string `json:"support_base_pattern_spacing,omitempty"`
	SupportBottomInterfaceSpacing       string `json:"support_bottom_interface_spacing,omitempty"`
	SupportBottomZDistance              string `json:"support_bottom_z_distance,omitempty"`
	SupportInterfaceSpacing             string `json:"support_interface_spacing,omitempty"`
	SupportTopZDistance                 string `json:"support_top_z_distance,omitempty"`
	SupportInterfaceBottomLayers        string `json:"support_interface_bottom_layers,omitempty"`
	SupportInterfaceTopLayers           string `json:"support_interface_top_layers,omitempty"`
	TreeSupportAngleSlow                string `json:"tree_support_angle_slow,omitempty"`
	TreeSupportBranchAngleOrganic       string `json:"tree_support_branch_angle_organic,omitempty"`
	TreeSupportBranchDiameterAngle      string `json:"tree_support_branch_diameter_angle,omitempty"`
	TreeSupportBranchDiameterDoubleWall string `json:"tree_support_branch_diameter_double_wall,omitempty"`
	TreeSupportBranchDiameterOrganic    string `json:"tree_support_branch_diameter_organic,omitempty"`
	TreeSupportBranchDistanceOrganic    string `json:"tree_support_branch_distance_organic,omitempty"`
	TreeSupportTipDiameter              string `json:"tree_support_tip_diameter,omitempty"`
	TreeSupportTopRate                  string `json:"tree_support_top_rate,omitempty"`

	// Line widths
	LineWidth                    string `json:"line_width,omitempty"`
	InitialLayerLineWidth        string `json:"initial_layer_line_width,omitempty"`
	OuterWallLineWidth           string `json:"outer_wall_line_width,omitempty"`
	InnerWallLineWidth           string `json:"inner_wall_line_width,omitempty"`
	SparseInfillLineWidth        string `json:"sparse_infill_line_width,omitempty"`
	InternalSolidInfillLineWidth string `json:"internal_solid_infill_line_width,omitempty"`
	TopSurfaceLineWidth          string `json:"top_surface_line_width,omitempty"`
	SupportLineWidth             string `json:"support_line_width,omitempty"`

	// Speeds
	TravelSpeed              string `json:"travel_speed"`
	OuterWallSpeed           string `json:"outer_wall_speed,omitempty"`
	InnerWallSpeed           string `json:"inner_wall_speed,omitempty"`
	SparseInfillSpeed        string `json:"sparse_infill_speed,omitempty"`
	InternalSolidInfillSpeed string `json:"internal_solid_infill_speed,omitempty"`
	TopSurfaceSpeed          string `json:"top_surface_speed,omitempty"`
	InitialLayerSpeed        string `json:"initial_layer_speed,omitempty"`
	InitialLayerInfillSpeed  string `json:"initial_layer_infill_speed,omitempty"`
	BridgeSpeed              string `json:"bridge_speed,omitempty"`
	InternalBridgeSpeed      string `json:"internal_bridge_speed,omitempty"`
	GapInfillSpeed           string `json:"gap_infill_speed,omitempty"`
	Overhang14Speed          string `json:"overhang_1_4_speed,omitempty"`
	Overhang24Speed          string `json:"overhang_2_4_speed,omitempty"`
	Overhang34Speed          string `json:"overhang_3_4_speed,omitempty"`
	Overhang44Speed          string `json:"overhang_4_4_speed,omitempty"`
	SmallPerimeterSpeed      string `json:"small_perimeter_speed,omitempty"`
	SmallPerimeterThreshold  string `json:"small_perimeter_threshold,omitempty"`

	// Accelerations
	DefaultAcceleration             string `json:"default_acceleration,omitempty"`
	TravelAcceleration              string `json:"travel_acceleration,omitempty"`
	OuterWallAcceleration           string `json:"outer_wall_acceleration,omitempty"`
	InnerWallAcceleration           string `json:"inner_wall_acceleration,omitempty"`
	SparseInfillAcceleration        string `json:"sparse_infill_acceleration,omitempty"`
	InternalSolidInfillAcceleration string `json:"internal_solid_infill_acceleration,omitempty"`
	TopSurfaceAcceleration          string `json:"top_surface_acceleration,omitempty"`
	InitialLayerAcceleration        string `json:"initial_layer_acceleration,omitempty"`
	BridgeAcceleration              string `json:"bridge_acceleration,omitempty"`

	// Jerk
	DefaultJerk      string `json:"default_jerk,omitempty"`
	TravelJerk       string `json:"travel_jerk,omitempty"`
	OuterWallJerk    string `json:"outer_wall_jerk,omitempty"`
	InnerWallJerk    string `json:"inner_wall_jerk,omitempty"`
	InfillJerk       string `json:"infill_jerk,omitempty"`
	TopSurfaceJerk   string `json:"top_surface_jerk,omitempty"`
	InitialLayerJerk string `json:"initial_layer_jerk,omitempty"`

	// Surface / output
	TopSurfacePattern string   `json:"top_surface_pattern,omitempty"`
	WipeOnLoops       string   `json:"wipe_on_loops,omitempty"`
	PostProcess       []string `json:"post_process,omitempty"`
	FilenameFormat    string   `json:"filename_format,omitempty"`

	// Prime tower
	PrimeTowerBrimWidth     string `json:"prime_tower_brim_width,omitempty"`
	EnablePrimeTower        string `json:"enable_prime_tower,omitempty"`
	WipeTowerNoSparseLayers string `json:"wipe_tower_no_sparse_layers,omitempty"`
	WipeTowerConeAngle      string `json:"wipe_tower_cone_angle,omitempty"`
	WipeTowerWallType       string `json:"wipe_tower_wall_type,omitempty"`
	PrimeTowerWidth         string `json:"prime_tower_width,omitempty"`
	PrimeVolume             string `json:"prime_volume,omitempty"`
	// Additional Orca profile keys (stable inferred types)
	AccelToDecel                                string   `json:"accel_to_decel,omitempty"`
	AccelToDecelFactor                          string   `json:"accel_to_decel_factor,omitempty"`
	AccelerationLimitMess                       string   `json:"acceleration_limit_mess,omitempty"`
	AccelerationLimitMessEnable                 string   `json:"acceleration_limit_mess_enable,omitempty"`
	AdaptiveLayerHeight                         string   `json:"adaptive_layer_height,omitempty"`
	AiInfill                                    string   `json:"ai_infill,omitempty"`
	AlignInfillDirectionToModel                 string   `json:"align_infill_direction_to_model,omitempty"`
	AlternateExtraWall                          string   `json:"alternate_extra_wall,omitempty"`
	ApplyTopSurfaceCompensation                 string   `json:"apply_top_surface_compensation,omitempty"`
	AvoidCrossingWallIncludesSupport            string   `json:"avoid_crossing_wall_includes_support,omitempty"`
	BottomColorPenetrationLayers                string   `json:"bottom_color_penetration_layers,omitempty"`
	BottomSolidInfillFlowRatio                  string   `json:"bottom_solid_infill_flow_ratio,omitempty"`
	BottomSurfaceDensity                        string   `json:"bottom_surface_density,omitempty"`
	BottomSurfacePattern                        string   `json:"bottom_surface_pattern,omitempty"`
	BridgeAngle                                 string   `json:"bridge_angle,omitempty"`
	BridgeDensity                               string   `json:"bridge_density,omitempty"`
	BridgeFlow                                  string   `json:"bridge_flow,omitempty"`
	BridgeInfillAcceleration                    string   `json:"bridge_infill_acceleration,omitempty"`
	BridgeNoSupport                             string   `json:"bridge_no_support,omitempty"`
	BrimEarsDetectionLength                     string   `json:"brim_ears_detection_length,omitempty"`
	BrimEarsMaxAngle                            string   `json:"brim_ears_max_angle,omitempty"`
	BrimObjectGap                               string   `json:"brim_object_gap,omitempty"`
	BrimWidth                                   string   `json:"brim_width,omitempty"`
	CalibFlowrateTopinfillSpecialOrder          string   `json:"calib_flowrate_topinfill_special_order,omitempty"`
	CircleCompensationManualOffset              string   `json:"circle_compensation_manual_offset,omitempty"`
	CompatiblePrintersCondition                 string   `json:"compatible_printers_condition,omitempty"`
	CounterboreHoleBridging                     string   `json:"counterbore_hole_bridging,omitempty"`
	DefaultJunctionDeviation                    string   `json:"default_junction_deviation,omitempty"`
	Description                                 string   `json:"description,omitempty"`
	DetectFloatingVerticalShell                 string   `json:"detect_floating_vertical_shell,omitempty"`
	DetectNarrowInternalSolidInfill             string   `json:"detect_narrow_internal_solid_infill,omitempty"`
	DetectOverhangWall                          string   `json:"detect_overhang_wall,omitempty"`
	DetectThinWall                              string   `json:"detect_thin_wall,omitempty"`
	DontFilterInternalBridges                   string   `json:"dont_filter_internal_bridges,omitempty"`
	DraftShield                                 string   `json:"draft_shield,omitempty"`
	ElefantFootCompensationLayers               string   `json:"elefant_foot_compensation_layers,omitempty"`
	EmbeddingWallIntoInfill                     string   `json:"embedding_wall_into_infill,omitempty"`
	EnableArcFitting                            string   `json:"enable_arc_fitting,omitempty"`
	EnableCircleCompensation                    string   `json:"enable_circle_compensation,omitempty"`
	EnableExtraBridgeLayer                      string   `json:"enable_extra_bridge_layer,omitempty"`
	EnableHeightSlowdown                        []string `json:"enable_height_slowdown,omitempty"`
	EnableSupport                               string   `json:"enable_support,omitempty"`
	EnableSupportIroning                        string   `json:"enable_support_ironing,omitempty"`
	EnableTowerInterfaceCooldownDuringTower     string   `json:"enable_tower_interface_cooldown_during_tower,omitempty"`
	EnableTowerInterfaceFeatures                string   `json:"enable_tower_interface_features,omitempty"`
	EnableWrappingDetection                     string   `json:"enable_wrapping_detection,omitempty"`
	EndGcode                                    string   `json:"end_gcode,omitempty"`
	EnforceSupportLayers                        string   `json:"enforce_support_layers,omitempty"`
	EnsureVerticalShellThickness                string   `json:"ensure_vertical_shell_thickness,omitempty"`
	ExcludeObject                               string   `json:"exclude_object,omitempty"`
	ExtraPerimetersOnOverhangs                  string   `json:"extra_perimeters_on_overhangs,omitempty"`
	ExtrusionRateSmoothingExternalPerimeterOnly string   `json:"extrusion_rate_smoothing_external_perimeter_only,omitempty"`
	FillMultiline                               string   `json:"fill_multiline,omitempty"`
	FilterOutGapFill                            string   `json:"filter_out_gap_fill,omitempty"`
	FirstLayerJerk                              string   `json:"first_layer_jerk,omitempty"`
	FirstXLayerFanSpeed                         string   `json:"first_x_layer_fan_speed,omitempty"`
	FlushIntoInfill                             string   `json:"flush_into_infill,omitempty"`
	FlushIntoObjects                            string   `json:"flush_into_objects,omitempty"`
	FlushIntoSupport                            string   `json:"flush_into_support,omitempty"`
	FuzzySkin                                   string   `json:"fuzzy_skin,omitempty"`
	FuzzySkinFirstLayer                         string   `json:"fuzzy_skin_first_layer,omitempty"`
	FuzzySkinNoiseType                          string   `json:"fuzzy_skin_noise_type,omitempty"`
	FuzzySkinOctaves                            string   `json:"fuzzy_skin_octaves,omitempty"`
	FuzzySkinPersistence                        string   `json:"fuzzy_skin_persistence,omitempty"`
	FuzzySkinPointDistance                      string   `json:"fuzzy_skin_point_distance,omitempty"`
	FuzzySkinScale                              string   `json:"fuzzy_skin_scale,omitempty"`
	FuzzySkinThickness                          string   `json:"fuzzy_skin_thickness,omitempty"`
	GapFillEnabled                              string   `json:"gap_fill_enabled,omitempty"`
	GapFillTarget                               string   `json:"gap_fill_target,omitempty"`
	GcodeAddLineNumber                          string   `json:"gcode_add_line_number,omitempty"`
	GcodeComments                               string   `json:"gcode_comments,omitempty"`
	GcodeLabelObjects                           string   `json:"gcode_label_objects,omitempty"`
	HoleToPolyhole                              string   `json:"hole_to_polyhole,omitempty"`
	HoleToPolyholeThreshold                     string   `json:"hole_to_polyhole_threshold,omitempty"`
	HoleToPolyholeTwisted                       string   `json:"hole_to_polyhole_twisted,omitempty"`
	IndependentSupportLayerHeight               string   `json:"independent_support_layer_height,omitempty"`
	IneternalBridgeSpeed                        string   `json:"ineternal_bridge_speed,omitempty"`
	InfillCombination                           string   `json:"infill_combination,omitempty"`
	InfillCombinationMaxLayerHeight             string   `json:"infill_combination_max_layer_height,omitempty"`
	InfillDirection                             string   `json:"infill_direction,omitempty"`
	InfillInsteadTopBottomSurfaces              string   `json:"infill_instead_top_bottom_surfaces,omitempty"`
	InfillLayerAcceleration                     string   `json:"infill_layer_acceleration,omitempty"`
	InfillLockDepth                             string   `json:"infill_lock_depth,omitempty"`
	InfillRotateStep                            string   `json:"infill_rotate_step,omitempty"`
	InfillShiftStep                             string   `json:"infill_shift_step,omitempty"`
	InitalLayerHeight                           string   `json:"inital_layer_height,omitempty"`
	InitalTravelSpeed                           string   `json:"inital_travel_speed,omitempty"`
	InitialLayerMinBeadWidth                    string   `json:"initial_layer_min_bead_width,omitempty"`
	InitialLayerPrintHeight                     string   `json:"initial_layer_print_height,omitempty"`
	InitialLayerTravelAcceleration              []string `json:"initial_layer_travel_acceleration,omitempty"`
	InitialLayerTravelSpeed                     string   `json:"initial_layer_travel_speed,omitempty"`
	InitialSolidInfillAcceleration              string   `json:"initial_solid_infill_acceleration,omitempty"`
	InitialTravelSpeed                          string   `json:"initial_travel_speed,omitempty"`
	Instantiation                               string   `json:"instantiation,omitempty"`
	InterfaceShells                             string   `json:"interface_shells,omitempty"`
	InterlockingBeam                            string   `json:"interlocking_beam,omitempty"`
	InterlockingBeamLayerCount                  string   `json:"interlocking_beam_layer_count,omitempty"`
	InterlockingBeamWidth                       string   `json:"interlocking_beam_width,omitempty"`
	InterlockingBoundaryAvoidance               string   `json:"interlocking_boundary_avoidance,omitempty"`
	InterlockingDepth                           string   `json:"interlocking_depth,omitempty"`
	InterlockingOrientation                     string   `json:"interlocking_orientation,omitempty"`
	InternalBridgeAngle                         string   `json:"internal_bridge_angle,omitempty"`
	InternalBridgeDensity                       string   `json:"internal_bridge_density,omitempty"`
	InternalBridgeFlow                          string   `json:"internal_bridge_flow,omitempty"`
	InternalBridgeSupportThickness              string   `json:"internal_bridge_support_thickness,omitempty"`
	InternalSolidInfillPattern                  string   `json:"internal_solid_infill_pattern,omitempty"`
	IroningAngle                                string   `json:"ironing_angle,omitempty"`
	IroningFlow                                 string   `json:"ironing_flow,omitempty"`
	IroningInset                                string   `json:"ironing_inset,omitempty"`
	IroningPattern                              string   `json:"ironing_pattern,omitempty"`
	IroningSpacing                              string   `json:"ironing_spacing,omitempty"`
	IroningSpeed                                string   `json:"ironing_speed,omitempty"`
	IroningSupportLayer                         string   `json:"ironing_support_layer,omitempty"`
	IroningType                                 string   `json:"ironing_type,omitempty"`
	IsInfillFirst                               string   `json:"is_infill_first,omitempty"`
	LatticeAngle1                               string   `json:"lattice_angle_1,omitempty"`
	LatticeAngle2                               string   `json:"lattice_angle_2,omitempty"`
	LayerHeight2                                string   `json:"layer_height,omitempty"`
	LayerHeigth                                 string   `json:"layer_heigth,omitempty"`
	LayerTimeSmoothing                          string   `json:"layer_time_smoothing,omitempty"`
	LayerTimeSmoothingThreshold                 string   `json:"layer_time_smoothing_threshold,omitempty"`
	LockedSkeletonInfillPattern                 string   `json:"locked_skeleton_infill_pattern,omitempty"`
	LockedSkinInfillPattern                     string   `json:"locked_skin_infill_pattern,omitempty"`
	MachinePrepareCompensationTime              string   `json:"machine_prepare_compensation_time,omitempty"`
	MakeOverhangPrintable                       string   `json:"make_overhang_printable,omitempty"`
	MakeOverhangPrintableAngle                  string   `json:"make_overhang_printable_angle,omitempty"`
	MakeOverhangPrintableHoleSize               string   `json:"make_overhang_printable_hole_size,omitempty"`
	MaterialFlowDependentTemperature            string   `json:"material_flow_dependent_temperature,omitempty"`
	MaterialFlowTempGraph                       string   `json:"material_flow_temp_graph,omitempty"`
	MaxBridgeLength                             string   `json:"max_bridge_length,omitempty"`
	MaxTravelDetourDistance                     string   `json:"max_travel_detour_distance,omitempty"`
	MinBeadWidth                                string   `json:"min_bead_width,omitempty"`
	MinFeatureSize                              string   `json:"min_feature_size,omitempty"`
	MinLengthFactor                             string   `json:"min_length_factor,omitempty"`
	MinSkirtLength                              string   `json:"min_skirt_length,omitempty"`
	MinWidthTopSurface                          string   `json:"min_width_top_surface,omitempty"`
	MinimumSparseInfillArea                     string   `json:"minimum_sparse_infill_area,omitempty"`
	MinimumSparseInfillThreshold                string   `json:"minimum_sparse_infill_threshold,omitempty"`
	MinimumSupportArea                          string   `json:"minimum_support_area,omitempty"`
	MmuSegmentedRegionInterlockingDepth         string   `json:"mmu_segmented_region_interlocking_depth,omitempty"`
	MmuSegmentedRegionMaxWidth                  string   `json:"mmu_segmented_region_max_width,omitempty"`
	OnlyOneWallFirstLayer                       string   `json:"only_one_wall_first_layer,omitempty"`
	OozePrevention                              string   `json:"ooze_prevention,omitempty"`
	OverhangReverseInternalOnly                 string   `json:"overhang_reverse_internal_only,omitempty"`
	OverhangReverseThreshold                    string   `json:"overhang_reverse_threshold,omitempty"`
	OverhangSpeedClassic                        string   `json:"overhang_speed_classic,omitempty"`
	OverrideFilamentScarfSeamSetting            string   `json:"override_filament_scarf_seam_setting,omitempty"`
	PerciseOuterWall                            string   `json:"percise_outer_wall,omitempty"`
	PerciseZHeight                              string   `json:"percise_z_height,omitempty"`
	PreStartFanTime                             []string `json:"pre_start_fan_time,omitempty"`
	PreciseZHeight                              string   `json:"precise_z_height,omitempty"`
	PreheatSteps                                string   `json:"preheat_steps,omitempty"`
	PreheatTime                                 string   `json:"preheat_time,omitempty"`
	PrimeTowerEnableFramework                   string   `json:"prime_tower_enable_framework,omitempty"`
	PrimeTowerEnhanceType                       string   `json:"prime_tower_enhance_type,omitempty"`
	PrimeTowerFlatIroning                       string   `json:"prime_tower_flat_ironing,omitempty"`
	PrimeTowerLiftHeight                        string   `json:"prime_tower_lift_height,omitempty"`
	PrimeTowerLiftSpeed                         string   `json:"prime_tower_lift_speed,omitempty"`
	PrimeTowerMaxSpeed                          string   `json:"prime_tower_max_speed,omitempty"`
	PrintExtruderId                             []string `json:"print_extruder_id,omitempty"`
	PrintExtruderVariant                        []string `json:"print_extruder_variant,omitempty"`
	PrintFlowRatio                              string   `json:"print_flow_ratio,omitempty"`
	PrintOrder                                  string   `json:"print_order,omitempty"`
	PrintSequence                               string   `json:"print_sequence,omitempty"`
	RaftExpansion                               string   `json:"raft_expansion,omitempty"`
	RaftFirstLayerDensity                       string   `json:"raft_first_layer_density,omitempty"`
	RaftFirstLayerExpansion                     string   `json:"raft_first_layer_expansion,omitempty"`
	ReduceCrossingWall                          string   `json:"reduce_crossing_wall,omitempty"`
	ReduceInfillRetraction                      string   `json:"reduce_infill_retraction,omitempty"`
	RenamedFrom                                 string   `json:"renamed_from,omitempty"`
	RoleBasedWipeSpeed                          string   `json:"role_based_wipe_speed,omitempty"`
	RotateSolidInfillDirection                  string   `json:"rotate_solid_infill_direction,omitempty"`
	ScarfAngleThreshold                         string   `json:"scarf_angle_threshold,omitempty"`
	ScarfJointFlowRatio                         string   `json:"scarf_joint_flow_ratio,omitempty"`
	ScarfJointSpeed                             string   `json:"scarf_joint_speed,omitempty"`
	ScarfOverhangThreshold                      string   `json:"scarf_overhang_threshold,omitempty"`
	SeamGap                                     string   `json:"seam_gap,omitempty"`
	SeamPlacementAwayFromOverhangs              string   `json:"seam_placement_away_from_overhangs,omitempty"`
	SeamPosition                                string   `json:"seam_position,omitempty"`
	SeamSlopeEntireLoop                         string   `json:"seam_slope_entire_loop,omitempty"`
	SeamSlopeGap                                string   `json:"seam_slope_gap,omitempty"`
	SeamSlopeInnerWalls                         string   `json:"seam_slope_inner_walls,omitempty"`
	SeamSlopeMinLength                          string   `json:"seam_slope_min_length,omitempty"`
	SeamSlopeStartHeight                        string   `json:"seam_slope_start_height,omitempty"`
	SeamSlopeSteps                              string   `json:"seam_slope_steps,omitempty"`
	SettingId                                   string   `json:"setting_id,omitempty"`
	SingleExtruderMultiMaterialPriming          string   `json:"single_extruder_multi_material_priming,omitempty"`
	SingleLoopDraftShield                       string   `json:"single_loop_draft_shield,omitempty"`
	SkeletonInfillDensity                       string   `json:"skeleton_infill_density,omitempty"`
	SkeletonInfillLineWidth                     string   `json:"skeleton_infill_line_width,omitempty"`
	SkinInfillDensity                           string   `json:"skin_infill_density,omitempty"`
	SkinInfillDepth                             string   `json:"skin_infill_depth,omitempty"`
	SkinInfillLineWidth                         string   `json:"skin_infill_line_width,omitempty"`
	SkirtDistance                               string   `json:"skirt_distance,omitempty"`
	SkirtHeight                                 string   `json:"skirt_height,omitempty"`
	SkirtStartAngle                             string   `json:"skirt_start_angle,omitempty"`
	SkirtType                                   string   `json:"skirt_type,omitempty"`
	SliceClosingRadius                          string   `json:"slice_closing_radius,omitempty"`
	SlicingMode                                 string   `json:"slicing_mode,omitempty"`
	SlowDownCurledPerimeters                    string   `json:"slow_down_curled_perimeters,omitempty"`
	SlowDownLayers                              string   `json:"slow_down_layers,omitempty"`
	SlowLayersCount                             string   `json:"slow_layers_count,omitempty"`
	SlowdownEndAcc                              []string `json:"slowdown_end_acc,omitempty"`
	SlowdownEndHeight                           []string `json:"slowdown_end_height,omitempty"`
	SlowdownEndSpeed                            []string `json:"slowdown_end_speed,omitempty"`
	SlowdownForCurledPerimeters                 string   `json:"slowdown_for_curled_perimeters,omitempty"`
	SlowdownStartAcc                            []string `json:"slowdown_start_acc,omitempty"`
	SlowdownStartHeight                         []string `json:"slowdown_start_height,omitempty"`
	SlowdownStartSpeed                          []string `json:"slowdown_start_speed,omitempty"`
	SmallAreaInfillFlowCompensation             string   `json:"small_area_infill_flow_compensation,omitempty"`
	SmoothCoefficient                           string   `json:"smooth_coefficient,omitempty"`
	SmoothSpeedDiscontinuityArea                string   `json:"smooth_speed_discontinuity_area,omitempty"`
	SolidInfillDirection                        string   `json:"solid_infill_direction,omitempty"`
	SolidInfillFilament                         string   `json:"solid_infill_filament,omitempty"`
	SolidInfillRotateTemplate                   string   `json:"solid_infill_rotate_template,omitempty"`
	SparseInfillAnchor                          string   `json:"sparse_infill_anchor,omitempty"`
	SparseInfillFilament                        string   `json:"sparse_infill_filament,omitempty"`
	SparseInfillLatticeAngle1                   string   `json:"sparse_infill_lattice_angle_1,omitempty"`
	SparseInfillLatticeAngle2                   string   `json:"sparse_infill_lattice_angle_2,omitempty"`
	SparseInfillPatter                          string   `json:"sparse_infill_patter,omitempty"`
	SpeedLimitToHeight                          string   `json:"speed_limit_to_height,omitempty"`
	SpeedLimitToHeightEnable                    string   `json:"speed_limit_to_height_enable,omitempty"`
	SpiralFinishingFlowRatio                    string   `json:"spiral_finishing_flow_ratio,omitempty"`
	SpiralMode                                  string   `json:"spiral_mode,omitempty"`
	SpiralModeMaxXySmoothing                    string   `json:"spiral_mode_max_xy_smoothing,omitempty"`
	SpiralModeSmooth                            string   `json:"spiral_mode_smooth,omitempty"`
	SpiralStartingFlowRatio                     string   `json:"spiral_starting_flow_ratio,omitempty"`
	StaggeredInnerSeams                         string   `json:"staggered_inner_seams,omitempty"`
	StandbyTemperatureDelta                     string   `json:"standby_temperature_delta,omitempty"`
	StartGcode                                  string   `json:"start_gcode,omitempty"`
	SupportCriticalRegionsOnly                  string   `json:"support_critical_regions_only,omitempty"`
	SupportExpansion                            string   `json:"support_expansion,omitempty"`
	SupportFilament                             string   `json:"support_filament,omitempty"`
	SupportInterfaceBottomSpacing               string   `json:"support_interface_bottom_spacing,omitempty"`
	SupportInterfaceFilament                    string   `json:"support_interface_filament,omitempty"`
	SupportInterfaceLoopPattern                 string   `json:"support_interface_loop_pattern,omitempty"`
	SupportInterfaceNotForBody                  string   `json:"support_interface_not_for_body,omitempty"`
	SupportInterfacePattern                     string   `json:"support_interface_pattern,omitempty"`
	SupportIroningDirection                     string   `json:"support_ironing_direction,omitempty"`
	SupportIroningFlow                          string   `json:"support_ironing_flow,omitempty"`
	SupportIroningInset                         string   `json:"support_ironing_inset,omitempty"`
	SupportIroningPattern                       string   `json:"support_ironing_pattern,omitempty"`
	SupportIroningSpacing                       string   `json:"support_ironing_spacing,omitempty"`
	SupportIroningSpeed                         string   `json:"support_ironing_speed,omitempty"`
	SupportMaterialSynchronizeLayers            string   `json:"support_material_synchronize_layers,omitempty"`
	SupportObjectFirstLayerGap                  string   `json:"support_object_first_layer_gap,omitempty"`
	SupportObjectXyDistance                     string   `json:"support_object_xy_distance,omitempty"`
	SupportOnBuildPlateOnly                     string   `json:"support_on_build_plate_only,omitempty"`
	SupportRemoveSmallOverhang                  string   `json:"support_remove_small_overhang,omitempty"`
	SupportStyle                                string   `json:"support_style,omitempty"`
	SupportThresholdAngle                       string   `json:"support_threshold_angle,omitempty"`
	SupportThresholdOverlap                     string   `json:"support_threshold_overlap,omitempty"`
	SupportType                                 string   `json:"support_type,omitempty"`
	SupportXyOverridesZ                         string   `json:"support_xy_overrides_z,omitempty"`
	SymmetricInfillYAxis                        string   `json:"symmetric_infill_y_axis,omitempty"`
	ThicBirdges                                 string   `json:"thic_birdges,omitempty"`
	ThickBridges                                string   `json:"thick_bridges,omitempty"`
	ThickInternalBridges                        string   `json:"thick_internal_bridges,omitempty"`
	TimelapseType                               string   `json:"timelapse_type,omitempty"`
	TopColorPenetrationLayers                   string   `json:"top_color_penetration_layers,omitempty"`
	TopSolidInfillFlowRatio                     string   `json:"top_solid_infill_flow_ratio,omitempty"`
	TopSurfaceDensity                           string   `json:"top_surface_density,omitempty"`
	TravelShortDistanceAcceleration             []string `json:"travel_short_distance_acceleration,omitempty"`
	TreeSupportAdaptiveLayerHeight              string   `json:"tree_support_adaptive_layer_height,omitempty"`
	TreeSupportAutoBrim                         string   `json:"tree_support_auto_brim,omitempty"`
	TreeSupportBramchDiameterAngle              string   `json:"tree_support_bramch_diameter_angle,omitempty"`
	TreeSupportBranchAngle                      string   `json:"tree_support_branch_angle,omitempty"`
	TreeSupportBranchDiameter                   string   `json:"tree_support_branch_diameter,omitempty"`
	TreeSupportBranchDistance                   string   `json:"tree_support_branch_distance,omitempty"`
	TreeSupportBrimWidth                        string   `json:"tree_support_brim_width,omitempty"`
	TreeSupportWallCount                        string   `json:"tree_support_wall_count,omitempty"`
	TreeSupportWithInfill                       string   `json:"tree_support_with_infill,omitempty"`
	Type                                        string   `json:"type,omitempty"`
	VerticalShellSpeed                          []string `json:"vertical_shell_speed,omitempty"`
	WallCount                                   string   `json:"wall_count,omitempty"`
	WallDirection                               string   `json:"wall_direction,omitempty"`
	WallDistributionCount                       string   `json:"wall_distribution_count,omitempty"`
	WallFilament                                string   `json:"wall_filament,omitempty"`
	WallGenerator                               string   `json:"wall_generator,omitempty"`
	WallInfillOrder                             string   `json:"wall_infill_order,omitempty"`
	WallLoopDirection                           string   `json:"wall_loop_direction,omitempty"`
	WallSequence                                string   `json:"wall_sequence,omitempty"`
	WallTransitionAngle                         string   `json:"wall_transition_angle,omitempty"`
	WallTransitionFilterDeviation               string   `json:"wall_transition_filter_deviation,omitempty"`
	WallTransitionLength                        string   `json:"wall_transition_length,omitempty"`
	WipeBeforeExternalLoop                      string   `json:"wipe_before_external_loop,omitempty"`
	WipeSpeed                                   string   `json:"wipe_speed,omitempty"`
	WipeTowerBridging                           string   `json:"wipe_tower_bridging,omitempty"`
	WipeTowerExtraFlow                          string   `json:"wipe_tower_extra_flow,omitempty"`
	WipeTowerExtraRibLength                     string   `json:"wipe_tower_extra_rib_length,omitempty"`
	WipeTowerExtraSpacing                       string   `json:"wipe_tower_extra_spacing,omitempty"`
	WipeTowerExtruder                           string   `json:"wipe_tower_extruder,omitempty"`
	WipeTowerFilament                           string   `json:"wipe_tower_filament,omitempty"`
	WipeTowerMaxPurgeSpeed                      string   `json:"wipe_tower_max_purge_speed,omitempty"`
	WipeTowerRibWidth                           string   `json:"wipe_tower_rib_width,omitempty"`
	WipeTowerRotationAngle                      string   `json:"wipe_tower_rotation_angle,omitempty"`
	XyContourCompensation                       string   `json:"xy_contour_compensation,omitempty"`
	ZDirectionOutwallSpeedContinuous            string   `json:"z_direction_outwall_speed_continuous,omitempty"`

	// Additional Orca profile keys (mixed shapes, kept flexible)
	CompatiblePrinters                   any `json:"compatible_printers,omitempty"`
	EnableOverhangSpeed                  any `json:"enable_overhang_speed,omitempty"`
	Notes                                any `json:"notes,omitempty"`
	OverhangTotallySpeed                 any `json:"overhang_totally_speed,omitempty"`
	SmallAreaInfillFlowCompensationModel any `json:"small_area_infill_flow_compensation_model,omitempty"`
	SupportInterfaceSpeed                any `json:"support_interface_speed,omitempty"`
	SupportSpeed                         any `json:"support_speed,omitempty"`
	TravelSpeedZ                         any `json:"travel_speed_z,omitempty"`
	WipingVolumesExtruders               any `json:"wiping_volumes_extruders,omitempty"`
}
